#!/usr/bin/env python

import os
import subprocess

nzs    = [32]
n_epch = 100
obetas = [1.0]
dbetas = [1.0]

for nz in nzs:
    for obeta in obetas:
        for dbeta in dbetas:
            print('obeta=%.2e, dbeta=%.2f' % (obeta, dbeta))

            logfile = 'log_o%.2e_d%.2e.txt' % (obeta, dbeta)

            # fmt: python dcgan.py <nz> <ortho_beta> <diag_beta> <num_epochs>

            sub_txt = "cd /u/xl/tjlane/cryoem/dynanet/particle_simulations/ortho/celeba && " +\
            "python ./dcgan.py %d %f %f %d >& %s" % (nz, obeta, dbeta, n_epch, logfile)

            cmd = 'sbatch -p ml -A ml --mem=64g --time=168:00:00 --job-name=dcgan -n 4 --gpus geforce_rtx_2080_ti:4 --wrap "%s"' % (sub_txt,)
            print('>>', cmd)
            subprocess.call(cmd, shell=True)


