#!/usr/bin/env python

import os
import subprocess

obetas = [1.0]
dbetas = [1e11, 1e12, 1e13, 1e14, 1e15, 1e16, 1e17, 1e18]
vbetas = [1.0]

for obeta in obetas:
    for dbeta in dbetas:
        for vbeta in vbetas:
            print('obeta=%.2e, dbeta=%.2f, vbeta=%.2f' % (obeta, dbeta, vbeta))

            logfile = 'log_o%.2e_d%.2e_v%.2e.txt' % (obeta, dbeta, vbeta)

            sub_txt = "cd /u/xl/tjlane/cryoem/dynanet/particle_simulations/ortho/mnist && " +\
            "python ./trainortho mnist --model-type mnistvae --epochs 50 --obeta %.2e --dbeta %.2e --vaebeta %.2e --batch-size 64 --latent-size 16 >& %s" % (obeta, dbeta, vbeta, logfile)

            cmd = 'bsub -q slacgpu -n 1 -gpu "num=1:gmodel=GeForceRTX2080Ti" "%s"' % sub_txt

            print('>>', cmd)
            subprocess.call(cmd, shell=True)


