#!/usr/bin/env python

import os
import subprocess

obetas = [7e4]
dbetas = [1.0]
vbetas = [0.6]

for obeta in obetas:
    for dbeta in dbetas:
        for vbeta in vbetas:
            print('obeta=%.2e, dbeta=%.2f, vbeta=%.2f' % (obeta, dbeta, vbeta))

            logfile = 'log_o%.2e_d%.2e_v%.2e.txt' % (obeta, dbeta, vbeta)

            sub_txt = "cd /u/xl/tjlane/cryoem/dynanet/particle_simulations/ortho/toys/semicirc_sigma2 && " +\
            "python ./trainortho ./bot_quarter_circle_sigma2.00.h5 --model-type vae --epochs 50 --obeta %.2e --dbeta %.2e --vaebeta %.2e --batch-size 32 >& %s" % (obeta, dbeta, vbeta, logfile)

            cmd = 'bsub -q slacgpu -n 1 -gpu "num=1:gmodel=GeForceRTX2080Ti" "%s"' % sub_txt

            print('>>', cmd)
            subprocess.call(cmd, shell=True)


