#!/bin/bash -l

#BSUB -J orthoAE
#BSUB -q slacgpu
#BSUB -n 1
#BSUB -gpu "num=1:mode=exclusive_process:j_exclusive=no:mps=no"
#BSUB -R "span[hosts=1]"
#BSUB -W 24:00
#BSUB -e run.err
#BSUB -o run.out

# setup env
# source /etc/profile.d/modules.sh
# export MODULEPATH=/usr/share/Modules/modulefiles:/opt/modulefiles
# module purge
# module load PrgEnv-gcc/4.8.5

# working directory
wd="/u/xl/tjlane/cryoem/dynanet/particle_simulations/ortho/toys/semicirc_sigma2"

cd ${wd}
nvidia-smi -L &> smi.txt
python ./trainortho ./bot_quarter_circle_sigma2.00.h5 --model-type ae --epochs 1 --obeta 1e-11 --dbeta 0.1 >& log.txt

