#!/usr/bin/env python

import os
import subprocess

nz     = 128
n_epch = 20
obetas = [100, 200, 300, 400, 500, 600, 700, 800, 900]
dbetas = [1.0]

for obeta in obetas:
    for dbeta in dbetas:
        print('obeta=%.2e, dbeta=%.2f' % (obeta, dbeta))

        logfile = 'log_o%.2e_d%.2e.txt' % (obeta, dbeta)

        # fmt: python dcgan.py <nz> <ortho_beta> <diag_beta> <num_epochs>

        sub_txt = "cd /u/xl/tjlane/cryoem/dynanet/particle_simulations/ortho/kdef && " +\
        "python /u/xl/tjlane/opt/orthonet/orthonet/dcgan.py %d %f %f %d >& %s" % (nz, obeta, dbeta, n_epch, logfile)

        cmd = 'bsub -q slacgpu -gpu "num=1:gmodel=GeForceRTX2080Ti" "%s"' % sub_txt

        print('>>', cmd)
        #subprocess.call(cmd, shell=True)


