#!/bin/bash -l

#BSUB -J dcgan
#BSUB -q slacgpu
#BSUB -n 16
#BSUB -gpu "num=1:mode=exclusive_process:j_exclusive=no:mps=no"
#BSUB -R "span[hosts=1]"
#BSUB -W 72:00
#BSUB -e run.err
#BSUB -o run.out

# setup env
# source /etc/profile.d/modules.sh
# export MODULEPATH=/usr/share/Modules/modulefiles:/opt/modulefiles
# module purge
# module load PrgEnv-gcc/4.8.5

# approx 3.5 min per simulate_pdb command

# working directory
wd=$HOME/cryoem/dynanet/particle_simulations/nolb/cryoEM_simulations/03_modes
cmd=$HOME/opt/orthonet/orthonet/dcgan.py

# cmds // python dcgan.py <nz> <ortho_beta> <num_epochs>
nvidia-smi -L
python $cmd 128 0.0 1


